name: .Net

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4.1.1
        
      - name: Extract version
        id: getversion
        run: |
          $xml = [xml](Get-Content path\to\your\.csproj)
          $version = $xml.Project.PropertyGroup.Version
          echo "::set-output name=VERSION::$version"
        shell: pwsh

      - name: Check version
        run: |
          $uri = "https://api.github.com/repos/${{ github.repository }}/releases/tags/v${{ steps.getversion.outputs.VERSION }}"
          $versionExists = Invoke-RestMethod -Method Get -Headers @{ Authorization = "Bearer $env:ACCESS_TOKEN" } -Uri $uri
          
          if ($null -ne $versionExists.name) {
            Write-Output "Version already exists"
            exit 1
          }
        shell: pwsh
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v2.0.0

      - name: Configure github packages as nuget source
        run: dotnet nuget add source --username EivindAntonsen --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/EivindAntonsen/index.json"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: |
          $project = 'DetectiveSpecs/DetectiveSpecs.csproj'
          $outputDirectory = "${{ runner.workspace }}\Staging\Build"
          
          dotnet publish $project -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true --output $outputDirectory

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DetectiveSpecs
          path: ${{ runner.workspace }}/Staging/Build/

      - name: Create Github Release
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: pwsh ./.github/scripts/CreateRelease.ps1 -accessToken $env:ACCESS_TOKEN -repository "EivindAntonsen/DetectiveSpecs" -version v${{ steps.getversion.outputs.VERSION }}
        shell: pwsh

      - name: Upload Release Asset
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: pwsh ./.github/scripts/UploadRelease.ps1 -accessToken $env:ACCESS_TOKEN -workspace ${{ runner.workspace }} -repository "EivindAntonsen/DetectiveSpecs" -releaseId v${{ steps.getversion.outputs.VERSION }}
        shell: pwsh