name: .Net

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v2.0.0
        
      - name: Configure github packages as nuget source
        run: dotnet nuget add source --username EivindAntonsen --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/EivindAntonsen/index.json"

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: |
          $project = 'DetectiveSpecs/DetectiveSpecs.csproj'
          $outputDirectory = "${{ runner.workspace }}\Staging\Build"
          
          dotnet publish $project -c Release -r win-x64 --self-contained true /p:PublishSingleFile=true --output $outputDirectory

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: DetectiveSpecs
          path: ${{ runner.workspace }}/Staging/Build/
          
      - name: Create Github Release
        run: |
          $body = @{
            tag_name = "v1.0.0"
            target_commitish = "master"
            name = "v1.0.0"
            body = "Latest automated release of Detective Specs"
            draft = $false
            prerelease = $false
            generate_release_notes = $false
          } | ConvertTo-Json

          Invoke-RestMethod -Uri "https://api.github.com/repos/EivindAntonsen/DetectiveSpecs/releases" -Method Post -Headers @{"Accept" = "application/vnd.github+json"; "Authorization" = "Bearer $env:GH_TOKEN"; "X-GitHub-Api-Version" = "2022-11-28"} -Body $body
        shell: pwsh