name: .Net

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4.1.1

      - name: Setup .NET 8.0
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: 8.0.x

      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v2.0.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      - name: Publish
        run: |
          $project = 'DetectiveSpecs/DetectiveSpecs.csproj'
          $outputDirectory = "${{ runner.workspace }}\Staging\Build"
          
          dotnet publish $project -c Release --output $outputDirectory

      - name: Package and Push to GitHub Packages
        run: |
          dotnet pack --configuration Release --output .
          dotnet nuget push "DetectiveSpecs.*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/EivindAntonsen/index.json"